EKS resources for user RBAC (#6)
* update k8s outputs

* add eks roles

* providers fix

* kube resources

* data fix

* turn off auto approve apply

* touchups

* separate tfsec gh action

* temp turn off eks

* add pr comment

* turn off auto apply

* test comment

* artifacts for terraform files

* another plan test in ci

* add pr comments back

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -10,8 +10,8 @@ on:
       - main
 
 concurrency:
-    group: ${{github.ref}}
-    cancel-in-progress: true
+  group: ${{github.ref}}
+  cancel-in-progress: true
 
 env:
   # Secrets
@@ -25,16 +25,19 @@ env:
   TF_VAR_region: ${{ vars.AWS_DEFAULT_REGION }}
   TF_VAR_ec2s: ${{ vars.EC2S }}
   TF_VAR_vpc_name: devsecops-cicd
-  TF_VAR_vpc_cidr: "10.0.0.0/16"
+  TF_VAR_vpc_cidr: '10.0.0.0/16'
   TF_VAR_private_subnet_cidr_blocks: '["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]'
   TF_VAR_public_subnet_cidr_blocks: '["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]'
   WORKING_DIR: ./live/dev
-
 
 jobs:
   terraform:
     name: 'Terraform'
     runs-on: ubuntu-latest
+    timeout-minutes: 20
+
+    permissions:
+      pull-requests: write
 
     defaults:
       run:
@@ -50,43 +53,67 @@ jobs:
           terraform_version: 1.6.5
 
       - name: Terraform Init
-        run: |
-          terraform init
+        id: init
+        run: terraform init
 
       - name: Upload Artifact
         uses: actions/upload-artifact@v4
         with:
           name: terraform-init-artifacts
+          include-hidden-files: true
           path: |
-            .terraform.lock.hcl
-            .terraform/
+            **/.terraform.lock.hcl
+            **/.terraform/
 
       - name: Terraform Format
-        run: |
-          terraform fmt -check
+        id: fmt
+        run: terraform fmt -check
 
       - name: Terraform Validate
-        run: |
-          terraform validate
-
-      - name: tfsec
-        uses: aquasecurity/tfsec-action@v1.0.0
-        with:
-          soft_fail: true
-          out: tfsec-results.json
-          format: json
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: tfsec-results
-          path: tfsec-results.json
+        id: validate
+        run: terraform validate
 
       - name: Terraform Plan
-        run: |
-          terraform plan -out=tfplan
+        id: plan
+        # continue for the PR comment, then fail after posting
+        continue-on-error: true
+        run: terraform plan  -no-color -input=false
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main'
-        run: |
-          terraform apply -auto-approve tfplan
+      - name: Update Pull Request
+        uses: actions/github-script@v7
+        if: github.event_name == 'pull_request'
+        env:
+          PLAN: ${{ steps.plan.outputs.stdout }}
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+
+            <details><summary>Show Plan</summary>
+
+            \`\`\`terraform\n
+            ${process.env.PLAN}
+            \`\`\`
+
+            </details>
+
+            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: output
+            })
+
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1
+
+      # Apply only if the PR is merged
+      # - name: Terraform Apply
+      #   if: ${{ github.event.pull_request.merged }}
+      #   run: terraform apply -auto-approve -input=false
